spring.application.name=fake-store-cartservice
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_PUBLIC_JWT_URL:http://auth-service:8081/api/internal/auth/.well-known/jwks.json}
server.port=8085
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}